// protoc -I . helloworld.proto --go_out=plugins=grpc:.
// protoc -I=. --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative helloworld.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//     protoc-gen-go v1.27.1
//     protoc        v3.15.1
// source: helloworld.proto

package proto

import (
    protoreflect "google.golang.org/protobuf/reflect/protoreflect"
    protoimpl "google.golang.org/protobuf/runtime/protoimpl"
    reflect "reflect"
    sync "sync"
)

const (
    // Verify that this generated code is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
    // Verify that runtime/protoimpl is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
    *x = HelloRequest{}
    if protoimpl.UnsafeEnabled {
        mi := &file_helloworld_proto_msgTypes[0]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *HelloRequest) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
    mi := &file_helloworld_proto_msgTypes[0]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
    return file_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
    if x != nil {
        return x.Name
    }
    return ""
}

type HelloReply struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
    *x = HelloReply{}
    if protoimpl.UnsafeEnabled {
        mi := &file_helloworld_proto_msgTypes[1]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *HelloReply) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
    mi := &file_helloworld_proto_msgTypes[1]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
    return file_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
    if x != nil {
        return x.Message
    }
    return ""
}

type AddIntRequest struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Value1 int32 `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
    Value2 int32 `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
}

func (x *AddIntRequest) Reset() {
    *x = AddIntRequest{}
    if protoimpl.UnsafeEnabled {
        mi := &file_helloworld_proto_msgTypes[2]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *AddIntRequest) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*AddIntRequest) ProtoMessage() {}

func (x *AddIntRequest) ProtoReflect() protoreflect.Message {
    mi := &file_helloworld_proto_msgTypes[2]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use AddIntRequest.ProtoReflect.Descriptor instead.
func (*AddIntRequest) Descriptor() ([]byte, []int) {
    return file_helloworld_proto_rawDescGZIP(), []int{2}
}

func (x *AddIntRequest) GetValue1() int32 {
    if x != nil {
        return x.Value1
    }
    return 0
}

func (x *AddIntRequest) GetValue2() int32 {
    if x != nil {
        return x.Value2
    }
    return 0
}

type AddIntReply struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Message int32 `protobuf:"varint,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddIntReply) Reset() {
    *x = AddIntReply{}
    if protoimpl.UnsafeEnabled {
        mi := &file_helloworld_proto_msgTypes[3]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *AddIntReply) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*AddIntReply) ProtoMessage() {}

func (x *AddIntReply) ProtoReflect() protoreflect.Message {
    mi := &file_helloworld_proto_msgTypes[3]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use AddIntReply.ProtoReflect.Descriptor instead.
func (*AddIntReply) Descriptor() ([]byte, []int) {
    return file_helloworld_proto_rawDescGZIP(), []int{3}
}

func (x *AddIntReply) GetMessage() int32 {
    if x != nil {
        return x.Message
    }
    return 0
}

type AddFloatRequest struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Value1 float32 `protobuf:"fixed32,1,opt,name=value1,proto3" json:"value1,omitempty"`
    Value2 float32 `protobuf:"fixed32,2,opt,name=value2,proto3" json:"value2,omitempty"`
}

func (x *AddFloatRequest) Reset() {
    *x = AddFloatRequest{}
    if protoimpl.UnsafeEnabled {
        mi := &file_helloworld_proto_msgTypes[4]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *AddFloatRequest) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*AddFloatRequest) ProtoMessage() {}

func (x *AddFloatRequest) ProtoReflect() protoreflect.Message {
    mi := &file_helloworld_proto_msgTypes[4]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use AddFloatRequest.ProtoReflect.Descriptor instead.
func (*AddFloatRequest) Descriptor() ([]byte, []int) {
    return file_helloworld_proto_rawDescGZIP(), []int{4}
}

func (x *AddFloatRequest) GetValue1() float32 {
    if x != nil {
        return x.Value1
    }
    return 0
}

func (x *AddFloatRequest) GetValue2() float32 {
    if x != nil {
        return x.Value2
    }
    return 0
}

type AddFloatReply struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Message float32 `protobuf:"fixed32,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddFloatReply) Reset() {
    *x = AddFloatReply{}
    if protoimpl.UnsafeEnabled {
        mi := &file_helloworld_proto_msgTypes[5]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *AddFloatReply) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*AddFloatReply) ProtoMessage() {}

func (x *AddFloatReply) ProtoReflect() protoreflect.Message {
    mi := &file_helloworld_proto_msgTypes[5]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use AddFloatReply.ProtoReflect.Descriptor instead.
func (*AddFloatReply) Descriptor() ([]byte, []int) {
    return file_helloworld_proto_rawDescGZIP(), []int{5}
}

func (x *AddFloatReply) GetMessage() float32 {
    if x != nil {
        return x.Message
    }
    return 0
}

var File_helloworld_proto protoreflect.FileDescriptor

var file_helloworld_proto_rawDesc = []byte{
    0x0a, 0x10, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f,
    0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
    0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
    0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
    0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
    0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f,
    0x0a, 0x0d, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
    0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
    0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
    0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x22,
    0x27, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
    0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
    0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x41, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x46,
    0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76,
    0x61, 0x6c, 0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x76, 0x61, 0x6c,
    0x75, 0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x18, 0x02, 0x20,
    0x01, 0x28, 0x02, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x22, 0x29, 0x0a, 0x0d, 0x41,
    0x64, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
    0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6d,
    0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x33, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65,
    0x72, 0x12, 0x28, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0d, 0x2e,
    0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x48,
    0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x65, 0x0a, 0x09, 0x41,
    0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x49,
    0x6e, 0x74, 0x12, 0x0e, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
    0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
    0x22, 0x00, 0x12, 0x2e, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x10,
    0x2e, 0x41, 0x64, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
    0x1a, 0x0e, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
    0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
    0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
    file_helloworld_proto_rawDescOnce sync.Once
    file_helloworld_proto_rawDescData = file_helloworld_proto_rawDesc
)

func file_helloworld_proto_rawDescGZIP() []byte {
    file_helloworld_proto_rawDescOnce.Do(func() {
        file_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworld_proto_rawDescData)
    })
    return file_helloworld_proto_rawDescData
}

var file_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_helloworld_proto_goTypes = []interface{}{
    (*HelloRequest)(nil),    // 0: HelloRequest
    (*HelloReply)(nil),      // 1: HelloReply
    (*AddIntRequest)(nil),   // 2: AddIntRequest
    (*AddIntReply)(nil),     // 3: AddIntReply
    (*AddFloatRequest)(nil), // 4: AddFloatRequest
    (*AddFloatReply)(nil),   // 5: AddFloatReply
}
var file_helloworld_proto_depIdxs = []int32{
    0, // 0: Greeter.SayHello:input_type -> HelloRequest
    2, // 1: AddServer.AddInt:input_type -> AddIntRequest
    4, // 2: AddServer.AddFloat:input_type -> AddFloatRequest
    1, // 3: Greeter.SayHello:output_type -> HelloReply
    3, // 4: AddServer.AddInt:output_type -> AddIntReply
    5, // 5: AddServer.AddFloat:output_type -> AddFloatReply
    3, // [3:6] is the sub-list for method output_type
    0, // [0:3] is the sub-list for method input_type
    0, // [0:0] is the sub-list for extension type_name
    0, // [0:0] is the sub-list for extension extendee
    0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_proto_init() }
func file_helloworld_proto_init() {
    if File_helloworld_proto != nil {
        return
    }
    if !protoimpl.UnsafeEnabled {
        file_helloworld_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*HelloRequest); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_helloworld_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*HelloReply); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_helloworld_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*AddIntRequest); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_helloworld_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*AddIntReply); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_helloworld_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*AddFloatRequest); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_helloworld_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*AddFloatReply); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
    }
    type x struct{}
    out := protoimpl.TypeBuilder{
        File: protoimpl.DescBuilder{
            GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
            RawDescriptor: file_helloworld_proto_rawDesc,
            NumEnums:      0,
            NumMessages:   6,
            NumExtensions: 0,
            NumServices:   2,
        },
        GoTypes:           file_helloworld_proto_goTypes,
        DependencyIndexes: file_helloworld_proto_depIdxs,
        MessageInfos:      file_helloworld_proto_msgTypes,
    }.Build()
    File_helloworld_proto = out.File
    file_helloworld_proto_rawDesc = nil
    file_helloworld_proto_goTypes = nil
    file_helloworld_proto_depIdxs = nil
}
